function [n, nRounded] = writeBulk(fid, cards, opts)
%writeBulk Writes bulk data entries (mni.io.tokenizeBulk output) in fixed
%field format, keeping the text of every field as it was read.
%
% Syntax:
%   >> deck = mni.io.readDeck('model.bdf');
%   >> fid = fopen('flat.bdf', 'w');
%   >> mni.validation.writeBulk(fid, deck.Bulk, 'Exclude', {'PARAM'});
%   >> fclose(fid);
%
% Each logical line (8 data fields) is written in small field format
% when its fields fit in 8 characters, otherwise in large field format
% (two lines of 4 x 16 characters, '*' continuation). Continuations are
% generated by Nastran (blank / '*' field 1, blank field 10). A large
% field line pair with a blank half would be a blank continuation, which
% Nastran rejects (QRG "Continuations", rule 5), so such a logical line is
% written in small field with its long real numbers rounded to 8
% characters ('nRounded' counts them).
%
% Options:
%   'Exclude' - entry names left out

arguments
    fid (1, 1) double
    cards struct
    opts.Exclude = {}
end
n = 0;
nRounded = 0;
for k = 1 : numel(cards)
    if any(strcmp(cards(k).Name, opts.Exclude))
        continue
    end
    f = upper(strtrim(cards(k).Fields));
    last = find(~cellfun(@isempty, f), 1, 'last');
    if isempty(last), last = 0; end
    f = [f(1 : last), repmat({''}, 1, mod(-last, 8))];
    nl = max(1, numel(f) / 8);
    if isempty(f), f = repmat({''}, 1, 8); end
    for l = 1 : nl
        seg = f((l - 1) * 8 + 1 : l * 8);
        long = cellfun(@numel, seg) > 8;
        blankHalf = all(cellfun(@isempty, seg(1 : 4))) || all(cellfun(@isempty, seg(5 : 8)));
        if any(long) && ~blankHalf && numel(cards(k).Name) < 8
            long16 = cellfun(@numel, seg) > 16;
            seg(long16) = cellfun(@(s) i_shorten(s, 16), seg(long16), 'UniformOutput', false);
            if l == 1, head = [cards(k).Name, '*']; else, head = '*'; end
            fprintf(fid, '%-8s%s\n', head, i_join(seg(1 : 4), 16));
            fprintf(fid, '%-8s%s\n', '*', i_join(seg(5 : 8), 16));
        else
            if any(long)
                seg(long) = cellfun(@(s) i_shorten(s, 8), seg(long), 'UniformOutput', false);
                nRounded = nRounded + nnz(long);
            end
            if l == 1, head = cards(k).Name; else, head = ''; end
            fprintf(fid, '%s\n', deblank(sprintf('%-8s%s', head, i_join(seg, 8))));
        end
    end
    n = n + 1;
end
end

function s = i_join(seg, w)
s = strjoin(cellfun(@(x) sprintf('%-*s', w, x), seg, 'UniformOutput', false), '');
end

function s = i_shorten(s, w)
%real number -> at most 'w' characters
v = str2double(s);
assert(~isnan(v), 'mni:validation:writeBulk', 'Field ''%s'' longer than %d characters.', s, w);
for p = w : -1 : 0
    s = upper(sprintf('%.*G', p, v));
    if ~contains(s, '.')
        e = strfind(s, 'E');
        if isempty(e), s = [s, '.']; else, s = [s(1 : e - 1), '.', s(e : end)]; end %#ok<AGROW>
    end
    s = strrep(strrep(s, 'E+0', 'E+'), 'E-0', 'E-');
    s = regexprep(s, '^(-?)0\.(\d)', '$1.$2');
    if numel(s) <= w, return, end
end
end
