classdef QrgSpec
    %QrgSpec Access to the MSC Nastran Quick Reference Guide layout specs.
    %
    % The specs are generated by tools/qrg/extract_qrg.py into
    % unit_testing/qrg/spec/*.json (see tools/qrg/README.md).
    %
    % Syntax:
    %   >> c = QrgSpec.card('CBEAM');              %card record (struct) or []
    %   >> [names, rc] = QrgSpec.formatFields('CBEAM');    %fields 2-9 of each row
    %   >> [vals, rc]  = QrgSpec.exampleFields('CBEAM');   %example values
    %   >> lines = QrgSpec.exampleLines('CBEAM');  %example as small-field text
    %   >> s = QrgSpec.sol(103);                   %SOL table entry
    %
    % Field positions are returned "flattened" the way Nastran reads them:
    % fields 2..9 of the parent line followed by fields 2..9 of each
    % continuation line. 'rc' holds the [row, field] of each flattened
    % position (field = 2..9).

    methods (Static)
        function s = bulk()
            %bulk Returns the decoded 'qrg_bulk.json' (cached).
            persistent data
            if isempty(data)
                data = QrgSpec.load('qrg_bulk.json');
            end
            s = data;
        end
        function s = exec()
            persistent data
            if isempty(data)
                data = QrgSpec.load('qrg_exec.json');
            end
            s = data;
        end
        function s = caseControl()
            persistent data
            if isempty(data)
                data = QrgSpec.load('qrg_case.json');
            end
            s = data;
        end
        function s = params()
            persistent data
            if isempty(data)
                data = QrgSpec.load('qrg_params.json');
            end
            s = data;
        end
        function tf = isAvailable()
            %isAvailable True if the spec files have been generated.
            tf = isfile(fullfile(QrgSpec.specDir, 'qrg_bulk.json'));
        end
        function d = specDir()
            d = fullfile(fileparts(mfilename('fullpath')), 'spec');
        end
        function c = card(name)
            %card Returns the record of the bulk data entry 'name' or [].
            cards = QrgSpec.bulk().cards;
            fn = matlab.lang.makeValidName(name);
            if isfield(cards, fn)
                c = cards.(fn);
            else
                c = [];
            end
        end
        function n = cardNames()
            %cardNames All bulk data entry names in the QRG.
            c = struct2cell(QrgSpec.bulk().cards);
            n = cellfun(@(x) x.name, c, 'UniformOutput', false);
        end
        function [names, rc] = formatFields(name, iFormat)
            %formatFields Flattened field names of format block 'iFormat'.
            if nargin < 2
                iFormat = 1;
            end
            c = QrgSpec.card(name);
            assert(~isempty(c) && numel(c.formats) >= iFormat, ...
                'QrgSpec:noFormat', 'No QRG format %d for ''%s''.', iFormat, name);
            [names, rc] = QrgSpec.flatten(QrgSpec.blockRows(c.formats, iFormat));
        end
        function [vals, rc, blk] = exampleFields(name, iExample)
            %exampleFields Flattened values of example block 'iExample'.
            if nargin < 2
                iExample = 1;
            end
            c = QrgSpec.card(name);
            assert(~isempty(c) && numel(c.examples) >= iExample, ...
                'QrgSpec:noExample', 'No QRG example %d for ''%s''.', iExample, name);
            [vals, rc] = QrgSpec.flatten(QrgSpec.blockRows(c.examples, iExample));
            blk = QrgSpec.block(c.examples, iExample);
        end
        function lines = exampleLines(name, iExample)
            %exampleLines QRG example written as small-field (8 column)
            %text lines, continuation lines with a blank field 1.
            if nargin < 2
                iExample = 1;
            end
            c = QrgSpec.card(name);
            rows = QrgSpec.blockRows(c.examples, iExample);
            lines = cell(numel(rows), 1);
            for i = 1 : numel(rows)
                r = rows{i};
                if i > 1
                    r{1} = '';  %automatic continuation
                end
                r{10} = '';
                lines{i} = deblank(sprintf('%-8s', r{1 : 9}));
            end
        end
        function f = field(name, fieldName)
            %field Describer record (spec / default) of a field or [].
            c = QrgSpec.card(name);
            f = [];
            if isempty(c) || isempty(c.fields)
                return
            end
            idx = strcmp({c.fields.name}, fieldName);
            if any(idx)
                f = c.fields(find(idx, 1));
            end
        end
        function s = sol(num)
            %sol SOL table entry (name / description) for solution 'num'.
            t = QrgSpec.exec().sol;
            fn = matlab.lang.makeValidName(num2str(num));
            if isfield(t, fn)
                s = t.(fn);
            else
                s = [];
            end
        end
    end

    methods (Static, Access = private)
        function s = load(fname)
            f = fullfile(QrgSpec.specDir, fname);
            assert(isfile(f), 'QrgSpec:missing', ['QRG spec ''%s'' not found. ', ...
                'Run tools/qrg/extract_qrg.py first.'], f);
            s = jsondecode(fileread(f));
        end
        function b = block(blocks, i)
            if iscell(blocks)
                b = blocks{i};
            else
                b = blocks(i);
            end
        end
        function rows = blockRows(blocks, i)
            b = QrgSpec.block(blocks, i);
            rows = b.rows;
            if ~iscell(rows) %single row decoded as a cellstr column
                rows = {rows};
            elseif ~isempty(rows) && ischar(rows{1})
                rows = {rows};
            end
            rows = cellfun(@(r) reshape(cellstr(r), 1, []), rows, 'UniformOutput', false);
        end
        function [vals, rc] = flatten(rows)
            vals = {};
            rc   = zeros(0, 2);
            for i = 1 : numel(rows)
                r = rows{i};
                r(end + 1 : 10) = {''};
                vals = [vals, r(2 : 9)]; %#ok<AGROW>
                rc   = [rc ; [repmat(i, 8, 1), (2 : 9)']]; %#ok<AGROW>
            end
        end
    end
end
