classdef AeroelasticSpline < mni.bulk.BulkData
    %AeroelasticSpline

    methods % construction
        function obj = AeroelasticSpline(varargin)

            %Initialise the bulk data sets
            addBulkDataSet(obj, 'SPLINE1', ...
                'BulkProps'  , {'EID', 'CAERO', 'BOX1', 'BOX2', 'SETG', 'DZ', 'METHOD', 'USAGE', 'NELEM', 'MELEM'}, ...
                'PropTypes'  , {'i'  , 'i'    , 'i'   , 'i'   , 'i'   , 'r' , 'c'     , 'c'    , 'i'    , 'i'}    , ...
                'PropDefault', {''   , ''     , ''    , ''    , ''    , 0.0 , 'IPS'   , 'BOTH' , 10     , 10}     , ...
                'IDProp'     , 'EID', ...
                'Connections', { ...
                'CAERO', 'mni.bulk.AeroPanel', 'AeroPanel', ...
                'SETG' , 'mni.bulk.List'     , 'StrucNode'});

            addBulkDataSet(obj, 'SPLINE2', ...
                'BulkProps'  , {'EID', 'CAERO', 'ID1', 'ID2', 'SETG', 'DZ', 'DTOR', 'CID', 'DTHX', 'DTHY', 'USAGE'}, ...
                'PropTypes'  , {'i'  , 'i'    , 'i'  , 'i'  , 'i'   , 'r' , 'r'   , 'i'  , 'r'   , 'r'   , 'c'}    , ...
                'PropDefault', {''   , ''     , ''   , ''   , ''    , 0.0 , 1.0   , 0    , 0.0   , 0.0   , 'BOTH'} , ...
                'IDProp'     , 'EID', ...
                'Connections', { ...
                'CAERO', 'mni.bulk.AeroPanel'  , 'AeroPanel', ...
                'SETG' , 'mni.bulk.List'       , 'StrucNode', ...
                'CID'  , 'mni.bulk.CoordSystem', 'CoordSystem'});

            addBulkDataSet(obj, 'SPLINE3', ...
                'BulkProps'  , {'EID', 'CAERO', 'BOXID', 'COMP', 'G1', 'C1', 'A1', 'G2', 'C2', 'A2', 'USAGE'}, ...
                'PropTypes'  , {'i'  , 'i'    , 'i'    , 'i'   , 'i' , 'i' , 'r' , 'i' , 'i' , 'r' , 'c'}    , ...
                'PropDefault', {''   , ''     , ''     , ''    , ''  , ''  , ''  , ''  , ''  , ''  , 'BOTH'} , ...
                'IDProp'     , 'EID', ...
                'Connections', { ...
                'CAERO', 'mni.bulk.AeroPanel', 'AeroPanel', ...
                'G1'   , 'mni.bulk.Node'     , 'StrucNode1', ...
                'G2'   , 'mni.bulk.Node'     , 'StrucNode2'});

            addBulkDataSet(obj, 'SPLINE4', ...
                'BulkProps'  , {'EID', 'CAERO', 'AELIST', 'b' ,'SETG', 'DZ', 'METH', 'USAGE', 'NELEM', 'MELEM', 'FTYPE', 'RCORE'}, ...
                'PropTypes'  , {'i'  , 'i'    , 'i'     , 'c' ,'i'   , 'r' , 'c'   , 'c'    , 'i'    , 'i'    , 'c'    , 'r'}    , ...
                'PropDefault', {''   , ''     , ''      , ''  , ''   , 0.0 , 'IPS' , 'BOTH' , 10     , 10     , 'WF2'  , 0.0}   , ...
                'IDProp'     , 'EID', ...
                'Connections', { ...
                'CAERO' , 'mni.bulk.AeroPanel', 'AeroPanel', ...
                'AELIST', 'mni.bulk.AeroList'     , 'AeroList' , ...
                'SETG'  , 'mni.bulk.List'     , 'StrucNode'});

            addBulkDataSet(obj, 'SPLINE5', ...
                'BulkProps'  , {'SID', 'CAERO', 'AELIST', 'b' , 'SETG', 'DZ', 'DTOR', 'CID', 'DTHX', 'DTHY', 'USAGE', 'METH', 'FTYPE', 'RCORE'}, ...
                'PropTypes'  , {'i'  , 'i'    , 'i'     , 'c' , 'i'   , 'r' , 'r'   , 'i'  , 'r'   , 'r'   , 'c'    , 'c'   , 'c'    , 'r'}    , ...
                'PropDefault', {''   , ''     , ''      , ''  , ''    , 0.0 , 1.0   , 0    , 0.0   , 0.0   , 'BOTH' , 'BEAM', 'WF2'  , NaN}   , ...
                'IDProp'     , 'SID', ...
                'Connections', { ...
                'CAERO' , 'mni.bulk.AeroPanel'  , 'AeroPanel', ...
                'AELIST', 'mni.bulk.AeroList'       , 'AeroList' , ...
                'SETG'  , 'mni.bulk.List'       , 'StrucNode', ...
                'CID'   , 'mni.bulk.CoordSystem', 'CoordSystem'});

            addBulkDataSet(obj, 'SPLINE6', ...
                'BulkProps'  , {'EID', 'CAERO', 'AELIST', 'b' , 'SETG', 'DZ', 'METHOD', 'USAGE', 'VSTYPE', 'VSLIST', 'I2VNUM', 'D2VNUM', 'METHVS', 'DZR', 'METHCON', 'NGRID', 'ELTOL', 'NCYCLE', 'AUGWEI'}, ...
                'PropTypes'  , {'i'  , 'i'    , 'i'     , 'c' , 'i'   , 'r' , 'c'     , 'c'    , 'c'     , 'i'     , 'i'     , 'i'     , 'c'     , 'r'  , 'c'      , 'i'    , 'r'    , 'i'     , 'r'}     , ...
                'PropDefault', {''   , NaN    , ''      , ''  , ''    , 0.0 , 'FPS6'  , 'BOTH' , 'AERO'  , NaN     , 3       , 3       , 'VS6'   , 0.0  , 'NODEPROX', 1      , 100.0  , 3       , 0.0}    , ...
                'IDProp'     , 'EID', ...
                'Connections', { ...
                'CAERO' , 'mni.bulk.AeroPanel', 'AeroPanel', ...
                'AELIST', 'mni.bulk.AeroList'     , 'AeroList' , ...
                'SETG'  , 'mni.bulk.List'     , 'StrucNode', ...
                'VSLIST', 'mni.bulk.List'     , 'VirtualSurfaceList'});

            addBulkDataSet(obj, 'SPLINE7', ...
                'BulkProps'  , {'EID', 'CAERO', 'AELIST', 'b' , 'SETG', 'DZ', 'DTOR', 'USAGE', 'CID', 'METHOD', 'DZR', 'IA2', 'EPSBM'}, ...
                'PropTypes'  , {'i'  , 'i'    , 'i'     , 'c' , 'i'   , 'r' , 'r'   , 'c'    , 'i'  , 'c'     , 'r'  , 'r'  , 'r'}    , ...
                'PropDefault', {''   , NaN    , ''      , ''  , ''    , 0.0 , 1.0   , 'BOTH' , 0    , 'FBS6'  , 0.0  , 1.0  , 0.01}  , ...
                'IDProp'     , 'EID', ...
                'Connections', { ...
                'CAERO' , 'mni.bulk.AeroPanel'  , 'AeroPanel', ...
                'AELIST', 'mni.bulk.AeroList'       , 'AeroList' , ...
                'SETG'  , 'mni.bulk.List'       , 'StrucNode', ...
                'CID'   , 'mni.bulk.CoordSystem', 'CoordSystem'});

            varargin = parse(obj, varargin{:});
            preallocate(obj);

        end
    end

    methods % visualisation
        function hg = drawElement(obj, FEModel, hAx, varargin)

            hg = [];

            if isempty(obj.AeroPanel)
                return
            end

            p = parseInput(varargin{:});

            % get Aerodynamic coordinate system
            ACSID = 0;
            if isprop(FEModel,'AEROS')
                ACSID = FEModel.AEROS.ACSID;
            elseif isprop(FEModel,'AERO')
                ACSID = FEModel.AERO.ACSID;
            end

            %get X vector in basic frame
            if ACSID == 0
                X_dir = [1;0;0];
            else
                X_dir = FEModel.CORD2R.getVector([1;0;0],ACSID);
            end

            %Grab the panel data
            PanelData = getPanelData(obj.AeroPanel,X_dir);
            if isempty(PanelData) || any(cellfun(@isempty, {PanelData.Coords}))
                return
            end

            switch obj.CardName
                case 'SPLINE1'
                    id1 = obj.BOX1;
                    id2 = obj.BOX2;
                case 'SPLINE2'
                    id1 = obj.ID1;
                    id2 = obj.ID2;
                case 'SPLINE3'
                    id1 = obj.ID1;
                    id2 = obj.ID2;
                case 'SPLINE4'
                    id1 = obj.AELIST;
                    id2 = obj.AELIST;
                case 'SPLINE5'
                    id1 = obj.AELIST;
                    id2 = obj.AELIST;
                case 'SPLINE6'
                    id1 = obj.AELIST;
                    id2 = obj.AELIST;
                case 'SPLINE7'
                    id1 = obj.AELIST;
                    id2 = obj.AELIST;
                otherwise
                    error('Update the draw method for new spline card.');
            end

            %Get panel numbers of splines
            panelIDs = arrayfun(@(ii) id1(ii) : id2(ii), 1 : obj.NumBulk, 'Unif', false);
            panelIDs = horzcat(panelIDs{:});
            idx      = ismember(PanelData.IDs, panelIDs);

            %Arrange vertex coordinates for vectorised plotting
            x = PanelData.Coords(idx, 1 : 4, 1)';
            y = PanelData.Coords(idx, 1 : 4, 2)';
            z = PanelData.Coords(idx, 1 : 4, 3)';

            %Plot
            h = patch(hAx, x, y, z, ...
                'Tag'      , 'Splined Aero Nodes', ...
                'FaceColor', 'k');

            h_panel = plot3(hAx, ...
                PanelData.Centre(:, 1), PanelData.Centre(:, 2), PanelData.Centre(:, 3), ...
                'LineStyle', 'none', 'Marker', 'diamond', 'MarkerFaceColor', 'k', 'MarkerEdgeColor', 'k');

            % plot structural nodes
            h_nodes = [];
            if ~isempty(obj.StrucNode.Nodes)
                ids = unique([obj.StrucNode.Gi{:}]);
                mask = ismember(obj.StrucNode.Nodes.GID, ids);
                structural_nodes = getDrawCoords(obj.StrucNode.Nodes,'Mode',p.Results.Mode,...
                    'Scale',p.Results.Scale,'Phase',p.Results.Phase);
                h_nodes = line(hAx, structural_nodes(1,mask), structural_nodes(2,mask), structural_nodes(3,mask), ...
                    'Marker', 'diamond', 'MarkerFaceColor', 'y','MarkerEdgeColor', 'k', 'LineStyle', 'none', 'Tag', 'Splined Aero Nodes','HandleVisibility','on');

            end

            h_all = hggroup(hAx, 'Tag', 'Splined Aero Nodes');
            set([h, h_panel, h_nodes], 'Parent', h_all);
            set([h, h_panel], 'HandleVisibility', 'off');
            hg = h_all;
        end
    end

end

function p = parseInput(varargin)
expectedModes = {'undeformed','deformed'};
p = inputParser;
addParameter(p, 'AddOffset', true, @(x)validateattributes(x, {'logical'}, {'scalar'}));
addParameter(p,'Mode','deformed',...
    @(x)any(validatestring(x,expectedModes)));
addParameter(p,'Scale',1);
addParameter(p,'Phase',0);
parse(p, varargin{:});
end