classdef AnalysisData < mni.bulk.BulkData
    %AnalysisData Describes a bulk dat entry which specifies data for a
    %finite element analysis.
    %    
    % Valid Bulk Data Types:
    %   - 'AERO'
    %   - 'AEROS'
    %   - 'EIGR'
    %   - 'EIGRL'   (blank V1 / V2 = NaN: no bound)
    %   - 'FLUTTER'
    %   - 'FREQ', 'FREQ1'
    %   - 'RANDPS'
    %   - 'MKAERO1' (blank m / k = NaN), 'MKAERO2'
    %   - 'TRIM', 'TRIM2' (all label / value pairs in 'Labels' / 'Values';
    %                      TRIM2 'FREE' -> NaN)
    %   - 'GUST', 'TSTEP', 'DIVERG'

    properties (Hidden = true)
        %TRIM / TRIM2 trim variables: labels (cellstr) and values per entry
        Labels = {};
        Values = {};
    end

    methods % construction
        function obj = AnalysisData(varargin)
            
            %Initialise the bulk data sets
            addBulkDataSet(obj, 'AERO', ...
                'BulkProps'  , {'ACSID', 'VELOCITY', 'REFC', 'RHOREF', 'SYMXZ', 'SYMXY'}, ...
                'PropTypes'  , {'i'    , 'r'       , 'r'   , 'r'     , 'r'    , 'r'    }, ...
                'PropDefault', {0      , 0         , 0     , 0       , 0      , 0      }, ...
                'AttrList'   , {'VELOCITY', {'nonnegative'}, 'REFC', {'nonnegative'}, 'RHOREF', {'nonnegative'}, ...
                'SYMXZ', {'integer'}, 'SYMXY', {'integer'}}, ...
                'Connections', {'ACSID', 'mni.bulk.CoordSystem', 'AeroCoordSys'});
                addBulkDataSet(obj, 'AEROS', ...
                'BulkProps'  , {'ACSID', 'RCSID', 'REFC', 'REFB', 'REFS', 'SYMXZ', 'SYMXY'}, ...
                'PropTypes'  , {'i'    , 'i'       , 'r'   , 'r'     , 'r'    , 'i', 'i'    }, ...
                'PropDefault', {0      , 0         , 0     , 0       , 0      , 0,0      }, ...
                'AttrList'   , {'REFC', {'nonnegative'}, 'REFB', {'nonnegative'}, 'REFS', {'nonnegative'}, ...
                'SYMXZ', {'integer'}, 'SYMXY', {'integer'}}, ...
                'Connections', {'ACSID', 'mni.bulk.CoordSystem', 'AeroCoordSys'});
            addBulkDataSet(obj, 'EIGR', ...
                'BulkProps'  , {'SID', 'METHOD', 'F1', 'F2', 'NE', 'ND',           'NORM', 'G', 'C'}, ...
                'PropTypes'  , {'i'  , 'c'     , 'r' , 'r' , 'i' , 'i' , 'b', 'b', 'c'   , 'i', 'i'}, ...
                'PropDefault', {''   , ''      , 0   , 0   , 0   , 0   , 'MASS', 0  , 0  }, ...    
                'IDProp'     , 'SID', ...
                'AttrList'   , {'NE', {'positive'}});            
            addBulkDataSet(obj, 'EIGRL', ...
                'BulkProps'  , {'SID', 'V1', 'V2', 'ND', 'MSGLVL', 'MAXSET', 'SHFSCL', 'NORM'}, ...
                'PropTypes'  , {'i'  , 'r' , 'r' , 'i' , 'r'     , 'r'     , 'r'     , 'c'   }, ...
                'PropDefault', {''   , NaN , NaN , 0   , 0       , 0       , 0       , 'MASS'}, ...
                'IDProp'     , 'SID', ...
                'SetMethod'  , {'V1', @validateRealOrBlank, 'V2', @validateRealOrBlank}, ...
                'AttrList'   , {'MSGLVL', {'integer', 'nonnegative', '<=' 4}});
            addBulkDataSet(obj, 'FLUTTER', ...
                'BulkProps'  , {'SID', 'METHOD', 'DENS', 'MACH', 'RFREQ', 'IMETH', 'NVALUE_OMAX', 'EPS'}, ...
                'PropTypes'  , {'i'  , 'c'     , 'i'   , 'i'   , 'i'    , 'c'    , 'r'          , 'r'}  , ...
                'PropDefault', {0    , ''      , 0     , 0     , 0      , 'L'    , 0            ,  1e-3}, ...
                'IDProp'     , 'SID', ...
                'Connections', {'DENS', 'FLFACT', 'Density', 'MACH', 'FLFACT', 'Mach', 'RFREQ', 'FLFACT', 'ReducedFreq'});
            addBulkDataSet(obj, 'FREQ1', ...
                'BulkProps'  , {'SID', 'F1', 'DF', 'NDF'}, ...
                'PropTypes'  , {'i'  , 'r' , 'r' , 'i'}  , ...
                'PropDefault', {''   , ''  , ''  , 0}    , ...
                'IDProp'     , 'SID', ...
                'AttrList'   , {'F1', {'nonnegative'}, 'DF', {'nonnegative'}});
            addBulkDataSet(obj, 'FREQ', ...
                'BulkProps'  , {'SID', 'Fi'}, ...
                'PropTypes'  , {'i'  , 'r' }, ...
                'PropDefault', {''   , []  }, ...
                'IDProp'     , 'SID', ...
                'ListProp'   , {'Fi'});
            addBulkDataSet(obj, 'RANDPS', ...
                'BulkProps'  , {'SID', 'J', 'K', 'X', 'Y', 'TID'}, ...
                'PropTypes'  , {'i'  , 'i', 'i', 'r', 'r', 'i'}  , ...
                'PropDefault', {''   , '' , '' , 0  , 0  , ''}   , ...            
                'IDProp'     , 'SID', ...
                'Connections', {'TID', 'mni.bulk.List', 'Table'});
            addBulkDataSet(obj, 'MKAERO1', ...
                'BulkProps'  , {'M', 'K'}, ...
                'PropTypes'  , {'r', 'r'}, ...
                'PropDefault', {NaN, NaN}, ...
                'PropMask'   , {'M', 8, 'K', 8}, ...
                'AttrList'   , {'M', {'nrows', 8}, 'K', {'nrows', 8}}, ...
                'SetMethod'  , {'M', @validateRealOrBlank, 'K', @validateRealOrBlank});
            addBulkDataSet(obj, 'MKAERO2', ...
                'BulkProps'  , {'Mi', 'Ki'}, ...
                'PropTypes'  , {'r' , 'r' }, ...
                'PropDefault', {[]  , []  }, ...
                'ListProp'   , {'Mi', 'Ki'});
            addBulkDataSet(obj, 'TRIM', ...
                'BulkProps'  , {'SID', 'MACH', 'Q', 'LABEL1', 'UX1', 'LABEL2', 'UX2', 'AEQR'}, ...
                'PropTypes'  , {'i'  , 'r'   , 'r', 'c'     , 'r'  , 'c'     , 'r'  , 'r'   }, ...
                'PropDefault', {''   , ''    , '' , ''      , NaN  , ''      , NaN  , 1.0   }, ...
                'IDProp'     , 'SID', ...
                'SetMethod'  , {'UX1', @validateRealOrBlank, 'UX2', @validateRealOrBlank});
            addBulkDataSet(obj, 'TRIM2', ...
                'BulkProps'  , {'SID', 'MACH', 'Q',                     'AEQR'}, ...
                'PropTypes'  , {'i'  , 'r'   , 'r', 'b', 'b', 'b', 'b', 'r'   }, ...
                'PropDefault', {''   , ''    , '' ,                     1.0   }, ...
                'IDProp'     , 'SID');
            addBulkDataSet(obj, 'GUST', ...
                'BulkProps'  , {'SID', 'DLOAD', 'WG', 'X0', 'V'}, ...
                'PropTypes'  , {'i'  , 'i'    , 'r' , 'r' , 'r'}, ...
                'PropDefault', {''   , ''     , ''  , ''  , '' }, ...
                'IDProp'     , 'SID');
            addBulkDataSet(obj, 'TSTEP', ...
                'BulkProps'  , {'SID', 'Ni', 'DTi', 'NOi'}, ...
                'PropTypes'  , {'i'  , 'i' , 'r'  , 'i'  }, ...
                'PropDefault', {''   , []  , []   , []   }, ...
                'IDProp'     , 'SID', ...
                'ListProp'   , {'Ni', 'DTi', 'NOi'});
            addBulkDataSet(obj, 'DIVERG', ...
                'BulkProps'  , {'SID', 'NROOT', 'Mi'}, ...
                'PropTypes'  , {'i'  , 'i'    , 'r' }, ...
                'PropDefault', {''   , 1      , []  }, ...
                'IDProp'     , 'SID', ...
                'ListProp'   , {'Mi'});
            varargin = parse(obj, varargin{:});
            preallocate(obj);
            if any(strcmp(obj.CardName, {'TRIM', 'TRIM2'}))
                obj.BulkAssignFunction = @assignTrimData;
                obj.EntryProps = {'Labels', 'Values'};
                obj.Labels = cell(1, obj.NumBulk);
                obj.Values = cell(1, obj.NumBulk);
            end

        end
    end
        
    methods % assigning data during import
        function assignTrimData(obj, propData, index, BulkMeta)
            %assignTrimData TRIM / TRIM2: fixed fields of the first line
            %plus the label / value pairs (QRG TRIM: LABEL1 UX1 LABEL2 UX2
            %on line 1, then LABELi UXi from line 2; TRIM2: pairs from
            %line 2, value 'FREE' allowed).
            f = strtrim(reshape(propData, 1, []));
            f(end + 1 : 8) = {''};
            assignCardData(obj, f(1 : 8), index, BulkMeta);
            if strcmp(obj.CardName, 'TRIM')
                pairs = [f(4 : 7), f(9 : end)];
            else
                pairs = f(9 : end);
            end
            pairs = pairs(~cellfun(@isempty, pairs));
            if mod(numel(pairs), 2) ~= 0
                error('mni:bulk:TRIM', '%s %s: label without a value.', obj.CardName, f{1});
            end
            obj.Labels{index} = pairs(1 : 2 : end);
            obj.Values{index} = str2double(pairs(2 : 2 : end)); %'FREE' -> NaN
        end
        function [bulkNames, bulkData] = parseH5DataGroup(obj, h5Struct)
            %parseH5DataGroup Parse the data in the h5 data group
            %'h5Struct' and return the bulk names and data.
            
            if ~strcmp(obj.CardName, 'EIGRL')
                error('Update code for new h5 entry.');
            end
            
            %Just need to index into the 'IDENTITY' field then pass it on
            [bulkNames, bulkData, ~] = mni.bulk.BulkData.parseH5Data(h5Struct.IDENTITY);
            
        end
        function assignH5BulkData(obj, bulkNames, bulkData)
            %assignH5BulkData Assigns the object data during the import
            %from a .h5 file.
            
            prpNames   = obj.CurrentBulkDataProps;
            
            %Build the prop data
            prpData       = cell(size(prpNames));
            prpData(ismember(prpNames, bulkNames)) = bulkData(ismember(bulkNames, prpNames));
            switch obj.CardName
                case 'MKAERO1'
                    m_lab = cellstr(strcat('M', num2str((1 : 8)')))';
                    prpData{ismember(prpNames, 'M')} = ...
                        vertcat(bulkData{ismember(bulkNames, m_lab)});
                    k_lab = cellstr(strcat('K', num2str((1 : 8)')))';
                    prpData{ismember(prpNames, 'K')} = ...
                        vertcat(bulkData{ismember(bulkNames, k_lab)});
                otherwise
                    
            end
            assignH5BulkData@mni.bulk.BulkData(obj, prpNames, prpData)
            
        end
    end
    
end

