classdef List < mni.bulk.BulkData
    %List Describes a set of bulk data that can have an arbitrary number of
    %data points.
    %
    % Valid Bulk Data Types:
    %   - AEFACT
    %   - SET1
    %   - ASET1
    %   - FLFACT
    %   - TABDMP1
    %   - TABLED1
    %   - TABRND1
    
    properties (Constant)
        ValidDampingType = {'G', 'CRIT', 'Q'};
        ValidAxisType    = {'LINEAR', 'LOG'};
    end
     
    methods % construction
        function obj = List(varargin)
            
            %Initialise the bulk data sets
            addBulkDataSet(obj, 'SET1', ...
                'BulkProps'  , {'SID', 'Gi'}, ...
                'PropTypes'  , {'i'  , 'r'} , ...
                'PropDefault', {''   , '' } , ...
                'IDProp'     , 'SID' , ...
                'ListProp'   , {'Gi'}, ...
                'H5ListName' , {'G1'}, ...
                'Connections', {'Gi', 'mni.bulk.Node', 'Nodes'});
            addBulkDataSet(obj, 'ASET1', ...
                'BulkProps'  , {'C', 'IDi'}, ...
                'PropTypes'  , {'c', 'i'}  , ...
                'PropDefault', {'' , '' }  , ...
                'ListProp'   , {'IDi'}     , ...
                'H5ListName' , {'ID'}      , ...
                'SetMethod'  , {'C', @validateDOF});
            addBulkDataSet(obj, 'ASET', ...
                'BulkProps'  , {'IDi','Ci'}, ...
                'PropTypes'  , {'i','i'}  , ...
                'PropDefault', {'' , '' }  , ...
                'ListProp'   , {'IDi','Ci'}     , ...
                'H5ListName' , {'ID','C'});
            addBulkDataSet(obj, 'FLFACT', ...
                'BulkProps'  , {'SID', 'Fi'}, ...
                'PropTypes'  , {'i'  , 'r' }, ...
                'PropDefault', {0    , 0   }, ...
                'IDProp'     , 'SID', ...
                'ListProp'   , {'Fi'}, ...
                'H5ListName' , {'FI'});
            addBulkDataSet(obj, 'TABDMP1', ...
                'BulkProps'  , {'TID', 'TYPE', 'Fi', 'Gi', 'Token'}, ...
                'PropTypes'  , {'i'  , 'c'   , 'r' , 'r' , 'c'}    , ...
                'PropDefault', {''   , 'G'   , ''  , ''  , ''}     , ...
                'IDProp'     , 'TID', ...
                'ListProp'   , {'Fi', 'Gi'}, ...
                'H5ListName' , {'F' , 'G' }, ...
                'SetMethod'  , {'TYPE', @validateTYPE});
            addBulkDataSet(obj, 'TABLED1', ...
                'BulkProps'  , {'TID', 'XAXIS' , 'YAXIS' , 'Xi', 'Yi'}, ...
                'PropTypes'  , {'i'  , 'c'     , 'c'     , 'r' , 'r'} , ...
                'PropDefault', {''   , 'LINEAR', 'LINEAR', 0   , 0}   , ...
                'IDProp'     , 'TID', ...
                'ListProp'   , {'Xi', 'Yi'}, ...
                'H5ListName' , {'X' , 'Y' }, ...
                'SetMethod'  , {'XAXIS', @validateAxisType, 'YAXIS', @validateAxisType});
            addBulkDataSet(obj, 'TABRND1', ...
                'BulkProps'  , {'TID', 'XAXIS' , 'YAXIS' , 'Fi', 'Gi'}, ...
                'PropTypes'  , {'i'  , 'c'     , 'c'     , 'r' , 'r'} , ...
                'PropDefault', {''   , 'LINEAR', 'LINEAR', 0   , 0}   , ...
                'IDProp'     , 'TID', ...
                'ListProp'   , {'Fi', 'Gi'}, ...
                'H5ListName' , {'F' , 'G' }, ...
                'SetMethod'  , {'XAXIS', @validateAxisType, 'YAXIS', @validateAxisType});
            
            varargin = parse(obj, varargin{:});
            preallocate(obj);            
            
        end
    end
    
    methods % assigning data during import
        function assignH5BulkData(obj, bulkNames, bulkData)
            %assignH5BulkData Assigns the object data during the import
            %from a .h5 file.

            prpNames   = obj.CurrentBulkDataProps;
            if ~any(strcmp(obj.CardName, obj.ValidBulkNames))
                error('Update code');
            end
            
            %Build the prop data
            prpData       = cell(size(prpNames));
            prpData(ismember(prpNames, bulkNames)) = bulkData(ismember(bulkNames, prpNames));

            assignH5BulkData@mni.bulk.BulkData(obj, prpNames, prpData)
        end
        
        function assignCardData(obj, propData, index, BulkMeta)
            %Pass to superclass
            
            %Ensure list properties are empty before assignment to prevent
            %data contamination from other cards.
            if isfield(obj.CurrentBulkDataStruct, 'ListProp')
                listProps = obj.CurrentBulkDataStruct.ListProp;
                cellfun(@(p) obj.setProperty(p, [], index), listProps);
            end

            assignCardData@mni.bulk.BulkData(obj, propData, index, BulkMeta);
            %Set the ID
            obj.ID(index) = obj.(obj.CurrentBulkDataStruct.IDProp)(index);
        end
    end
    
    methods % validation TODO - Pass in the valid tokens as an extra argument!!
        function validateTYPE(obj, val, prpName, varargin)
            validateThenSetString(obj, val, prpName, obj.ValidDampingType);            
        end
        function validateAxisType(obj, val, prpName, varargin)
            validateThenSetString(obj, val, prpName, obj.ValidAxisType);
        end
        function validateThenSetString(obj, val, prpName, toks)
            val = upper(val);
            msg = sprintf(['Expected ''%s'' to be a cell array ', ...
                'of strings with each element being one of the following '  , ...
                'tokens:\n\n\t- %s\n\n'], prpName, strjoin(toks, ', '));
            assert(iscellstr(val), msg); %#ok<ISCLSTR>
            assert(all(ismember(val, toks)), msg);
            obj.(prpName) = val;      
        end
    end
    
end
