classdef Load < mni.bulk.BulkData
    %Load Static loads (QRG ch.9).
    %
    % Valid Bulk Data Types:
    %   - 'FORCE'  : SID G CID F N1 N2 N3
    %   - 'MOMENT' : SID G CID M N1 N2 N3
    %   - 'GRAV'   : SID CID A N1 N2 N3 MB
    %   - 'LOAD'   : SID S S1 L1 S2 L2 ...

    methods % construction
        function obj = Load(varargin)
            addBulkDataSet(obj, 'FORCE', ...
                'BulkProps'  , {'SID', 'G', 'CID', 'F', 'N'}, ...
                'PropTypes'  , {'i'  , 'i', 'i'  , 'r', 'r'}, ...
                'PropDefault', {''   , '' , 0    , 0  , 0  }, ...
                'IDProp'     , 'SID', ...
                'PropMask'   , {'N', 3}, ...
                'AttrList'   , {'N', {'nrows', 3}}, ...
                'Connections', {'G', 'mni.bulk.Node', 'Nodes'});
            addBulkDataSet(obj, 'MOMENT', ...
                'BulkProps'  , {'SID', 'G', 'CID', 'M', 'N'}, ...
                'PropTypes'  , {'i'  , 'i', 'i'  , 'r', 'r'}, ...
                'PropDefault', {''   , '' , 0    , 0  , 0  }, ...
                'IDProp'     , 'SID', ...
                'PropMask'   , {'N', 3}, ...
                'AttrList'   , {'N', {'nrows', 3}}, ...
                'Connections', {'G', 'mni.bulk.Node', 'Nodes'});
            addBulkDataSet(obj, 'GRAV', ...
                'BulkProps'  , {'SID', 'CID', 'A', 'N', 'MB'}, ...
                'PropTypes'  , {'i'  , 'i'  , 'r', 'r', 'i' }, ...
                'PropDefault', {''   , 0    , '' , 0  , 0   }, ...
                'IDProp'     , 'SID', ...
                'PropMask'   , {'N', 3}, ...
                'AttrList'   , {'N', {'nrows', 3}}, ...
                'SetMethod'  , {'MB', @validateIntOrBlank});
            addBulkDataSet(obj, 'LOAD', ...
                'BulkProps'  , {'SID', 'S', 'Si', 'Li'}, ...
                'PropTypes'  , {'i'  , 'r', 'r' , 'i' }, ...
                'PropDefault', {''   , '' , []  , []  }, ...
                'IDProp'     , 'SID', ...
                'ListProp'   , {'Si', 'Li'});
            varargin = parse(obj, varargin{:});
            preallocate(obj);
        end
    end

    methods
        function V = vectors(obj)
            %vectors FORCE / MOMENT / GRAV: scaled vector (3 x N) in the
            %coordinate system CID of each entry.
            switch obj.CardName
                case 'FORCE'
                    V = obj.N .* obj.F;
                case 'MOMENT'
                    V = obj.N .* obj.M;
                case 'GRAV'
                    V = obj.N .* obj.A;
                otherwise
                    error('mni:bulk:Load', 'No vector for %s entries.', obj.CardName);
            end
        end
    end
end
