classdef Material < mni.bulk.BulkData
    %Material Describes the properties of a bulk.Beam object.
    %
    % The definition of the 'BeamProp' object matches that of the PBEAM
    % bulk data type from MSC.Nastran.
    %
    % Valid Bulk Data Types:
    %   - 'MAT1'

    methods % construction
        function obj = Material(varargin)
                
            %Initialise the bulk data sets
            addBulkDataSet(obj, 'MAT1', ...
                'BulkProps'  , {'MID', 'E', 'G', 'NU', 'RHO', 'A', 'TREF', 'GE', 'ST', 'SC', 'SS', 'MCSID'}, ...
                'PropTypes'  , {'i'  , 'r', 'r', 'r' , 'r'  , 'r', 'r'   , 'r' , 'r' , 'r' , 'r' , 'i'}    , ...
                'PropDefault', {''   , 0  , 0  , 0   , 0    , 0  , 0     , 0   , 0   , 0   , 0   , 0}      , ...
                'IDProp'     , 'MID', ...
                'AttrList'   , {'E', {'nonnegative'}, 'G', {'nonnegative'}, 'NU',  {'>', -1, '<', 0.5}     , ...
                'RHO', {'nonnegative'}, 'ST', {'nonnegative'}, 'SC', {'nonnegative'}, 'SS', {'nonnegative'}});

            addBulkDataSet(obj, 'MAT8', ...
                'BulkProps'  , {'MID', 'E1', 'E2', 'NU12', 'G12', 'G1Z', 'G2Z', 'RHO', 'A1', 'A2', 'TREF', 'Xt', 'Xc', 'Yt', 'Yc', 'S', 'GE', 'F12', 'STRN'}, ...
                'PropTypes'  , {'i'  , 'r' , 'r' , 'r'   , 'r'  , 'r'  , 'r'  , 'r'  , 'r' , 'r' , 'r'   , 'r' , 'r' , 'r' , 'r' , 'r', 'r' , 'r'  , 'r'}    , ...
                'PropDefault', {''   , 0.0 , 0.0 , 0.0   , 0.0  , 0.0  , 0.0  , 0.0  , 0.0 , 0.0 , 0.0   , 0.0 , 0.0 , 0.0 , 0.0 , 0.0, 0.0 , 0.0  , 0.0}      , ...
                'IDProp'     , 'MID', ...
                'AttrList'   , {'E1' , {'nonnegative'}, 'E2' , {'nonnegative'}, 'G12', {'nonnegative'}, ...
                'G1Z', {'nonnegative'}, 'G2Z', {'nonnegative'}, 'RHO', {'nonnegative'}, ...
                'Xt' , {'nonnegative'}, 'Xc' , {'nonnegative'}, 'Yt' , {'nonnegative'}, ...
                'Yc' , {'nonnegative'}, 'S'  , {'nonnegative'}});

            addBulkDataSet(obj, 'MAT3', ...
                'BulkProps'  , {'MID', 'EX', 'ETH', 'EZ', 'NUXTH', 'NUXTHZ', 'NUZX', 'RHO', 'GZX', 'AX', 'ATH', 'AZ', 'TREF', 'GE'}, ...
                'PropTypes'  , {'i'  , 'r' , 'r'  , 'r' , 'r'    , 'r'     , 'r'   , 'r'  , 'r'  , 'r' , 'r'  , 'r' , 'r'   , 'r'}    , ...
                'PropDefault', {''   , 0.0 , 0.0  , 0.0 , 0.0    , 0.0     , 0.0   , 0.0  , 0.0  , 0.0 , 0.0  , 0.0 , 0.0   , 0.0}      , ...
                'IDProp'     , 'MID', ...
                'AttrList'   , {'EX', {'nonnegative'}, 'ETH', {'nonnegative'}, 'EZ', {'nonnegative'}, 'RHO', {'nonnegative'}, 'GZX', {'nonnegative'}});
            
            varargin = parse(obj, varargin{:});
            preallocate(obj);
            
        end
    end
    
end
