function t = solTable()
%solTable MSC Nastran solution sequences (QRG, Executive Control "SOL",
%remark 6, Table 2).
%
% Output: struct array with fields Number, Name, Description.

data = { ...
    101, 'SESTATIC', 'Statics (linear steady state heat transfer, alternate reduction, inertia relief)'; ...
    103, 'SEMODES' , 'Normal modes'; ...
    105, 'SEBUCKL' , 'Buckling (static analysis, alternate reduction, inertia relief)'; ...
    106, 'NLSTATIC', 'Nonlinear or linear statics'; ...
    107, 'SEDCEIG' , 'Direct complex eigenvalues'; ...
    108, 'SEDFREQ' , 'Direct frequency response'; ...
    109, 'SEDTRAN' , 'Direct transient response'; ...
    110, 'SEMCEIG' , 'Modal complex eigenvalues'; ...
    111, 'SEMFREQ' , 'Modal frequency response'; ...
    112, 'SEMTRAN' , 'Modal transient response'; ...
    114, 'CYCSTATX', 'Cyclic statics (alternate reduction)'; ...
    115, 'CYCMODE' , 'Cyclic normal modes'; ...
    116, 'CYCBUCKL', 'Cyclic buckling'; ...
    118, 'CYCFREQ' , 'Cyclic direct frequency response'; ...
    128, 'SENLHARM', 'Nonlinear harmonic response'; ...
    129, 'NLTRAN'  , 'Nonlinear or linear transient response'; ...
    144, 'AESTAT'  , 'Static aeroelastic response'; ...
    145, 'SEFLUTTR', 'Aerodynamic flutter'; ...
    146, 'SEAERO'  , 'Aeroelastic response'; ...
    153, 'NLSCSH'  , 'Static structural and/or steady state heat transfer'; ...
    159, 'NLTCSH'  , 'Transient structural and/or transient heat transfer'; ...
    200, 'DESOPT'  , 'Design optimization'; ...
    400, 'NONLIN'  , 'Nonlinear static and implicit transient analysis'; ...
    700, 'NLTRAN'  , 'Nonlinear explicit transient analysis'};
t = cell2struct(data, {'Number', 'Name', 'Description'}, 2);
end
